services:
  - type: web
    name: msquare-academy
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false # Iska matlab aap Atlas ki link manual daalenge security ke liye
      - key: NODE_VERSION
        value: 18.0.0
});